// Generated by lezer-generator, taken from @replit/codemirror-lang-csharp@6.2.0.
// Vendored so the daemon never loads the editor-only runtime those packages
// pull in at import time (@codemirror/autocomplete, view, state). Only pure
// Lezer primitives are used here. See packages/highlight/src/svelte for the
// same treatment applied to Svelte.
export const interpStringContent = 296;
export const interpStringBrace = 297;
export const interpStringEnd = 298;
export const interpVStringContent = 299;
export const interpVStringBrace = 300;
export const interpVStringEnd = 301;
