// Generated by lezer-generator, taken from @replit/codemirror-lang-csharp@6.2.0.
// Vendored so the daemon never loads the editor-only runtime those packages
// pull in at import time (@codemirror/autocomplete, view, state). Only pure
// Lezer primitives are used here. See packages/highlight/src/svelte for the
// same treatment applied to Svelte.
import { ExternalTokenizer } from "@lezer/lr";
import {
  interpStringBrace,
  interpStringContent,
  interpStringEnd,
  interpVStringBrace,
  interpVStringContent,
  interpVStringEnd,
} from "./terms.js";

const quote = 34,
  backslash = 92,
  braceL = 123,
  braceR = 125;
export const interpString = new ExternalTokenizer((input) => {
  for (let i = 0; ; i++) {
    switch (input.next) {
      case -1:
        if (i > 0) input.acceptToken(interpStringContent);
        return;
      case quote:
        if (i > 0) input.acceptToken(interpStringContent);
        else input.acceptToken(interpStringEnd, 1);
        return;
      case braceL:
        if (input.peek(1) === braceL) input.acceptToken(interpStringContent, 2);
        else input.acceptToken(interpStringBrace);
        return;
      case braceR:
        if (input.peek(1) === braceR) input.acceptToken(interpStringContent, 2);
        return;
      case backslash:
        const next = input.peek(1);
        if (next === braceL || next === braceR) return;
        input.advance();
      // FALLTHROUGH
      default:
        input.advance();
    }
  }
});
export const interpVString = new ExternalTokenizer((input) => {
  for (let i = 0; ; i++) {
    switch (input.next) {
      case -1:
        if (i > 0) input.acceptToken(interpVStringContent);
        return;
      case quote:
        if (input.peek(1) === quote) input.acceptToken(interpVStringContent, 2);
        else if (i > 0) input.acceptToken(interpVStringContent);
        else input.acceptToken(interpVStringEnd, 1);
        return;
      case braceL:
        if (input.peek(1) === braceL) input.acceptToken(interpVStringContent, 2);
        else input.acceptToken(interpVStringBrace);
        return;
      case braceR:
        if (input.peek(1) === braceR) input.acceptToken(interpVStringContent, 2);
        return;
      default:
        input.advance();
    }
  }
});
