// Generated by lezer-generator, taken from @replit/codemirror-lang-nix@6.0.1.
// Vendored so the daemon never loads the editor-only runtime those packages
// pull in at import time (@codemirror/autocomplete, view, state). Only pure
// Lezer primitives are used here. See packages/highlight/src/svelte for the
// same treatment applied to Svelte.
export const strContent = 63;
export const strDollarBrace = 64;
export const strEnd = 65;
export const escapeSequence = 66;
export const indStrContent = 67;
export const indStrDollarBrace = 68;
export const indStrEnd = 69;
export const indEscapeSequence = 70;
